# Generated by Django 2.2 on 2019-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=500, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[(1, 'Person'), (2, 'Institution')], max_length=20)),
                ('location', models.CharField(max_length=500, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
