# Generated by Django 2.2 on 2019-04-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids',
                                               to='agent.Investor')),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('min_interest', models.FloatField()),
                ('status',
                 models.CharField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Finished')], max_length=20, null=True)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='agent.Bank')),
            ],
            options={
                'ordering': ('transaction',),
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments',
                                          to='investment.Bid')),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids',
                                    to='investment.Loan'),
        ),
    ]
