# Generated by Django 2.2 on 2019-04-02 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0003_auto_20190402_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='interest',
        ),
    ]
