# Generated by Django 2.2 on 2019-04-02 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0004_auto_20190402_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='interest',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='min_interest',
            new_name='min_interest_rate',
        ),
    ]
