# Generated by Django 2.2 on 2019-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0005_auto_20190402_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_to_bid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
