# Generated by Django 2.2 on 2019-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0006_loan_amount_to_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_to_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], null=True),
        ),
    ]
