# Generated by Django 2.2 on 2019-04-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investment', '0007_auto_20190403_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='time_duration_in_auction',
            field=models.IntegerField(default=1440),
            preserve_default=False,
        ),
    ]
